### ISSUE TITLE
V2 Additions/Comments(or, features not being implemented in V1)

### ISSUE THREAD

**Issue by jybjones** [NSS-Cohort-9/minitwit#23]
Some features don't need to be addressed in V1, but should be addressed in later versions. 

Ex: currently this is a Desktop application. V2 might be for Mobile/Tablet, etc...

**Comment by sscotth** [comment]
Can you be more specific? I can tag specific issues, but this is vague. Can you make a new issue mentioning something specific so that we can have discussions about that issue?
