### ISSUE TITLE
Change App Name from minitwit to atmebro

### ISSUE THREAD

**Issue by sscotth** [NSS-Cohort-9/minitwit#4]
Ideas?

**Comment by sscotth** [comment]
mrn #1

**Comment by NoahYarian** [comment]
twtr?

**Comment by edstros** [comment]
I really don't have a problem with MiniTwit. It's descriptive, it's shows a relationship with Twitter and kind of catchy. Maybe though we don't want to show relationship with Twitter.
Since the main advantage of this app is that it is a shorter version of Twitter, I like twtr, too. But how does one say that? 
Maybe we could call it Shortr? Or Updatr?

**Comment by Capocaccia** [comment]
Chirp.  Since its one word its not a tweet its a chirp.

**Comment by james-logan** [comment]
Tweeter.... the more accurate version of twitter

**Comment by NoahYarian** [comment]
Holla

**Comment by james-logan** [comment]
TalkAt.... because life is about talking _at_ people. Talking _with_ them is too much work

**Comment by jybjones** [comment]
WORD (playoff of the app called YO, but in this case, it's a WORD)

**Comment by ChelseaRucker** [comment]
What about "Word Up"... the ratchets will love it. By the way do we have a target market or nah?

**Comment by jspencersharpe** [comment]
Whapsatt. Like Whatsapp, but you're whapping people with your words.

**Comment by SimoneGonzalez** [comment]
28

**Comment by ccates23** [comment]
Chatter

**Comment by ChelseaRucker** [comment]
ChitChat

**Comment by johnwquarles** [comment]
WYRDS GONE WYLD

**Comment by jspencersharpe** [comment]
ChitChad

**Comment by jspencersharpe** [comment]
Chadder

**Comment by ChelseaRucker** [comment]
SmallTalk

**Comment by ChelseaRucker** [comment]
Parley

**Comment by jybjones** [comment]
WORD!!!!!!!!!!!!!!!!!!!!!!
Blurp
Foo
Bizz
Buzz
?queso?

**Comment by johnwquarles** [comment]
BUFFALO WYLD WYRDS

**Comment by GregDick** [comment]
Que? So?

**Comment by Capocaccia** [comment]
jaja

**Comment by SimoneGonzalez** [comment]
@meBro

**Comment by SimoneGonzalez** [comment]
caption

**Comment by ccates23** [comment]
gorjeo

**Comment by james-logan** [comment]
skype

**Comment by ccates23** [comment]
pío

**Comment by Capocaccia** [comment]
Name suggestions end at 10AM!  I will be making a poll we can vote on after 10AM.

**Comment by james-logan** [comment]
grunt <this one actually makes sense

**Comment by calebgregory** [comment]
whoppr - a la http://wac.450f.edgecastcdn.net/80450F/b1017online.com/files/2013/03/robin-eggs-instagram.jpg

**Comment by jspencersharpe** [comment]
TA1K (like Talk but one word, get it?)

**Comment by ChelseaRucker** [comment]
Uno

**Comment by calebgregory** [comment]
snack

**Comment by james-logan** [comment]
Oon  --- (which is the phonetic pronunciation of "une" which is "one" in french)

**Comment by calebgregory** [comment]
bump - playing on the addictive qualities of social media

**Comment by Capocaccia** [comment]
The name that won the voting was @meBro so this issue can be closed.

**Comment by sscotth** [comment]
Still need to remove all mentions of "minitwit"
